# This workflow will build a MuleSoft project and deploy to CloudHub

name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
env:
  GLOBAL_NEXUS_USERNAME : ${{ secrets.nexus_username }}
  GLOBAL_NEXUS_PASSWORD : ${{ secrets.nexus_password }}
  GLOBAL_PLATFORM_CLIENTID : ${{ secrets.Client_Id }}
  GLOBAL_PLATFORM_SECRET : ${{ secrets.Client_Secret }}  
  GLOBAL_PLATFORM_USERNAME: ${{ secrets.USERNAME }}
  GLOBAL_PLATFORM_PASSWORD: ${{ secrets.PASSWORD }}
  GLOBAL_SETTINGS: ${{ secrets.Settings }}
    
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Build and Deploy with Maven
      run: mvn clean -B package deploy -DmuleDeploy -s settings.xml
    
