# This workflow will build a MuleSoft project and deploy to CloudHub

name: Cloudhub deployment with Maven [Main]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  GLOBAL_NEXUS_USERNAME : ${{ secrets.nexus_username }}
  GLOBAL_NEXUS_PASSWORD : ${{ secrets.nexus_password }}
  GLOBAL_PLATFORM_CLIENTID : ${{ secrets.Client_Id }}
  GLOBAL_PLATFORM_SECRET : ${{ secrets.Client_Secret }}  
  GLOBAL_PLATFORM_USERNAME: ${{ secrets.USERNAME }}
  GLOBAL_PLATFORM_PASSWORD: ${{ secrets.PASSWORD }}
  GLOBAL_SETTINGS: ${{ secrets.Settings }}
  GLOBAL_GRANT_TYPE: ${{ secrets.GRANT_TYPE }}
  GLOBAL_APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
  GLOBAL_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
  GLOBAL_WORKER_TYPE: ${{ secrets.WORKER_TYPE }}
  GLOBAL_REGION: ${{ secrets.REGION }}
  GLOBAL_WORKERS: ${{ secrets.WORKERS }}
  
    
jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    environment: main
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Deploy with Maven
      run: mvn -s settings.xml deploy -DmuleDeploy 
